/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#834691",
        "on-primary": "#ffffff",
        "primary-container": "#d793e4",
        "on-primary-container": "#60266f",
        "primary-fixed": "#fcd6ff",
        "primary-fixed-dim": "#f3aeff",
        "on-primary-fixed": "#340042",
        "on-primary-fixed-variant": "#682e77",
        "inverse-primary": "#f3aeff",
        secondary: "#705574",
        "on-secondary": "#ffffff",
        "secondary-container": "#fbd7fd",
        "on-secondary-container": "#775b7b",
        "secondary-fixed": "#fbd7fd",
        "secondary-fixed-dim": "#debce0",
        "on-secondary-fixed": "#29132e",
        "on-secondary-fixed-variant": "#573e5c",
        tertiary: "#546500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9fb54b",
        "on-tertiary-container": "#384500",
        surface: "#fff7fb",
        "surface-dim": "#e1d7de",
        "surface-bright": "#fff7fb",
        "surface-variant": "#eadfe7",
        "surface-tint": "#834691",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf1f8",
        "surface-container": "#f6ebf2",
        "surface-container-high": "#f0e5ec",
        "surface-container-highest": "#eadfe7",
        "on-surface": "#1f1a1f",
        "on-surface-variant": "#4e434e",
        "inverse-surface": "#342f34",
        "inverse-on-surface": "#f9eef5",
        background: "#fff7fb",
        "on-background": "#1f1a1f",
        outline: "#80737f",
        "outline-variant": "#d1c2cf",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        "container-max": "1280px",
        gutter: "24px",
        xs: "4px",
        md: "24px",
        "margin-mobile": "16px",
        lg: "48px",
        sm: "12px",
        base: "8px",
      },
      fontFamily: {
        headline: ["Geist", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "mono-sm": ["12px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
